### PR TITLE
Implement alignment

### PR DESCRIPTION
**Pull request by thisirs**
Adding blank pages if needed at the end

Not fully tested but does that sound good to you?

### CODE REVIEW

**Comment by metaist** [comment]
Can you explain a little bit about the use case for blank pages?

**Comment by thisirs** [comment]
For example, if you want to merge several documents and print them, a (eventual) blank page makes sure that a given sheet contains only one document and is not mixing two of them...

**Comment by no1xsyzy** [comment]
Then why not add a separate blank page between them?
And most documents should have headers and footers, which can prevent mixing.

**Comment by thisirs** [comment]
@no1xsyzy A blank page is not always necessary nor desirable. I just don't want a document to start on an even page which might happen if the previous document ends on an odd page. This patch makes sure that a new document starts on an odd page inserting or not a blank page.

**Comment by no1xsyzy** [comment]
Then this description makes more sense. You should've described more about "if needed".
However, there might be some mistake in your edits. I will comment on your code in file changes.

**Pull request closed without merging**
